# sam_checkpoint = "/Users/liudun/Desktop/anno_tools/AnnotationTools/sam_vit_h_4b8939.pth"
sam_checkpoint = "/root/AnnotationTools/sam_vit_h_4b8939.pth"
device = "cuda"
model_type = "default"
db_name="/root/AnnotationTools/test.sqlite"